version: '3.9'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.5.4
    secrets:
      - ovh_endpoint
      - ovh_application_key
      - ovh_application_secret
      - ovh_consumer_key
    environment:
      - TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
      - TRAEFIK_API=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER=true
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER_ACME_EMAIL=julian.husson@icloud.com
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER_ACME_STORAGE=/letsencrypt/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER_ACME_DNSCHALLENGE_PROVIDER=ovh
      - TRAEFIK_CERTIFICATESRESOLVERS_RESOLVER_ACME_DNSCHALLENGE_DELAYBEFORECHECK=0
      - TZ=Europe/Paris
      - OVH_ENDPOINT_FILE=/run/secrets/ovh_endpoint
      - OVH_APPLICATION_KEY_FILE=/run/secrets/ovh_application_key
      - OVH_APPLICATION_SECRET_FILE=/run/secrets/ovh_application_secret
      - OVH_CONSUMER_KEY_FILE=/run/secrets/ovh_consumer_key
    ports:
      - '80:80'
      - '443:443'
    labels:
      - "traefik.enable=true"
      #Redirect routers
      - 'traefik.http.routers.websecure-redirection.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.websecure-redirection.entrypoints=web'
      - 'traefik.http.routers.websecure-redirection.middlewares=redirect'
      #Redirect middlewares
      - 'traefik.http.middlewares.redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect.redirectscheme.permanent=true'
      #Dashboard routers
      - 'traefik.http.routers.dashboard.service=api@internal'
      - "traefik.http.routers.dashboard.rule=Host(`traefik.julian-husson.com`)"
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls.certresolver=resolver'
      - "traefik.http.routers.dashboard.middlewares=auth"
      #Dashboard services
      - 'traefik.http.services.api@internal.loadbalancer.server.port=8080'
      #Dashboard middlewares
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$nHzdz0PwkISTLz3EARM/c.6g2Knqmp.RecHLm93zk2FchP.RO2S/u"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './letsencrypt:/letsencrypt'
    networks:
      - web
secrets:
  ovh_endpoint:
    file: "./secrets/ovh_endpoint.txt"
  ovh_application_key:
    file: "secrets/ovh_application_key.txt"
  ovh_application_secret:
    file: "./secrets/ovh_application_secret.txt"
  ovh_consumer_key:
    file: "./secrets/ovh_consumer_key.txt"
networks:
  web:
    external: true
